/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 C:\Users\MADIHA\Desktop\BlenSpark\Blenspark-revamp\public\BMW.glb --transform 
Files: C:\Users\MADIHA\Desktop\BlenSpark\Blenspark-revamp\public\BMW.glb [16.6MB] > C:\Users\MADIHA\Desktop\BlenSpark\Blenspark-revamp\BMW-transformed.glb [1.58MB] (90%)
*/

import React, { useRef, useEffect } from 'react';
import { useGLTF, useAnimations } from '@react-three/drei';
import glb from './BMW-transformed.glb';

export function BMW({ onRefsReady, ...props }) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF(glb);
  const { actions } = useAnimations(animations, group);

  // Existing refs for car parts
  const chassisRef = useRef();
  const doorFLRef = useRef();
  const doorFRRef = useRef();
  const doorRLRef = useRef();
  const doorRRRef = useRef();
  const dashRef = useRef();
  const tailgateRef = useRef();
  const headlightsRef = useRef();
  const tailLightsRef = useRef();
  const doorFLRefglass = useRef();
  const doorRLRefglass = useRef();
  const doorFLSignalRef = useRef();
  const doorFLLeatherRef = useRef();
  const doorFLRefleather1 = useRef();
  const doorFRWheelRef = useRef();
  const doorFRSignalRef = useRef();
  const doorInRef = useRef();
  const doorFRRefleather1 = useRef();
  const tireRef = useRef();
  const leather1Ref = useRef();
  const tailgateGlassRef = useRef();

  // New refs for missing meshes
  const body2001Ref = useRef();
  const bodyshellRef = useRef();
  const bodyshellLogoRef = useRef();
  const chassisCarpetRef = useRef();
  const dashCarbonInteriorRef = useRef();
  const dashScreenRef = useRef();
  useEffect(() => {
    if (actions) {
      console.log("Available animation names:", Object.keys(actions));
    }
  }, []);
  useEffect(() => {
    const refs = {
      Chassis: chassisRef,
      DoorFL: doorFLRef,
      DoorFR: doorFRRef,
      DoorRL: doorRLRef,
      DoorRR: doorRRRef,
      Tailgate: tailgateRef,
      Headlights: headlightsRef,
      TailLights: tailLightsRef,
      DoorFLGlass: doorFLRefglass,
      DoorRLGlass: doorRLRefglass,
      DoorFLSignal: doorFLSignalRef,
      DoorFLLeather: doorFLLeatherRef,
      DoorFLLeather1: doorFLRefleather1,
      DoorFRWheel: doorFRWheelRef,
      DoorFRSignal: doorFRSignalRef,
      DoorIn: doorInRef,
      DoorFRLeather1: doorFRRefleather1,
      Tire: tireRef,
      Leather1: leather1Ref,
      TailgateGlass: tailgateGlassRef,
      Body2001: body2001Ref,
      Bodyshell: bodyshellRef,
      BodyshellLogo: bodyshellLogoRef,
      ChassisCarpet: chassisCarpetRef,
      DashCarbonInterior: dashCarbonInteriorRef,
      DashScreen: dashScreenRef,
    };
    onRefsReady(refs);
  }, [onRefsReady]);

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="inmx7m60i_chassis" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="inmx7m60i_doorfl" position={[0.796, -0.811, -0.352]} >
            <mesh
              name="inmx7m60i_doorfl_inmx7m60i_black_0"
              geometry={nodes.inmx7m60i_doorfl_inmx7m60i_black_0.geometry}
              material={materials.PaletteMaterial001}
              ref={doorFLRef}
            />
            <mesh
              name="inmx7m60i_doorfl_inmx7m60i_glass_0"
              geometry={nodes.inmx7m60i_doorfl_inmx7m60i_glass_0.geometry}
              material={materials.PaletteMaterial002}
              ref={doorFLRefglass}
            />
            <mesh
              name="inmx7m60i_doorfl_inmx7m60i_leather1_0"
              geometry={nodes.inmx7m60i_doorfl_inmx7m60i_leather1_0.geometry}
              material={materials.inmx7m60i_leather1}
              ref={doorFLLeatherRef}
            />
            <mesh
              name="inmx7m60i_doorfl_inmx7m60i_signalL_0"
              geometry={nodes.inmx7m60i_doorfl_inmx7m60i_signalL_0.geometry}
              material={materials.PaletteMaterial003}
              ref={doorFLSignalRef}
            />
          </group>
          <group name="inmx7m60i_doorfr" position={[-0.807, -0.818, 0.651]} >
            <mesh
              name="inmx7m60i_doorfr_inmx7m60i_black_0"
              geometry={nodes.inmx7m60i_doorfr_inmx7m60i_black_0.geometry}
              material={materials.PaletteMaterial001}
              ref={doorFRRef}
            />
            <mesh
              name="inmx7m60i_doorfr_inmx7m60i_glass_0"
              geometry={nodes.inmx7m60i_doorfr_inmx7m60i_glass_0.geometry}
              material={materials.PaletteMaterial002}
            />
            <mesh
              name="inmx7m60i_doorfr_inmx7m60i_leather1_0"
              geometry={nodes.inmx7m60i_doorfr_inmx7m60i_leather1_0.geometry}
              material={materials.inmx7m60i_leather1}
              ref={doorFRRefleather1}
            />
            <mesh
              name="inmx7m60i_doorfr_inmx7m60i_signalL_0"
              geometry={nodes.inmx7m60i_doorfr_inmx7m60i_signalL_0.geometry}
              material={materials.PaletteMaterial003}
              ref={doorFRSignalRef}
            />
          </group>
          <group name="inmx7m60i_doorrl" position={[0.804, 0.176, 0.677]} >
            <mesh
              name="inmx7m60i_doorrl_inmx7m60i_black_0"
              geometry={nodes.inmx7m60i_doorrl_inmx7m60i_black_0.geometry}
              material={materials.PaletteMaterial001}
              ref={doorRLRef}
            />
            <mesh
              name="inmx7m60i_doorrl_inmx7m60i_glass_0"
              geometry={nodes.inmx7m60i_doorrl_inmx7m60i_glass_0.geometry}
              material={materials.PaletteMaterial002}
              ref={doorRLRefglass}
            />
            <mesh
              name="inmx7m60i_doorrl_inmx7m60i_leather1_0"
              geometry={nodes.inmx7m60i_doorrl_inmx7m60i_leather1_0.geometry}
              material={materials.inmx7m60i_leather1}
            />
          </group>
          <group name="inmx7m60i_doorrr" position={[-0.804, 0.165, 0.69]} >
            <mesh
              name="inmx7m60i_doorrr_inmx7m60i_black_0"
              geometry={nodes.inmx7m60i_doorrr_inmx7m60i_black_0.geometry}
              material={materials.PaletteMaterial001}
              ref={doorRRRef}
            />
            <mesh
              name="inmx7m60i_doorrr_inmx7m60i_glass_0"
              geometry={nodes.inmx7m60i_doorrr_inmx7m60i_glass_0.geometry}
              material={materials.PaletteMaterial002}
            />
            <mesh
              name="inmx7m60i_doorrr_inmx7m60i_leather1_0"
              geometry={nodes.inmx7m60i_doorrr_inmx7m60i_leather1_0.geometry}
              material={materials.inmx7m60i_leather1}
            />
          </group>
          <mesh
            name="inmx7m60i_chassis_inmx7m60i_carpet_0"
            geometry={nodes.inmx7m60i_chassis_inmx7m60i_carpet_0.geometry}
            material={materials.inmx7m60i_carpet}
            ref={chassisCarpetRef}
          />
          <mesh
            name="inmx7m60i_chassis_inmx7m60i_leather1_0"
            geometry={nodes.inmx7m60i_chassis_inmx7m60i_leather1_0.geometry}
            material={materials.inmx7m60i_leather1}
            ref={leather1Ref}
          />
        </group>
        <mesh
          name="inmx7m60i_body2001_bmwx72_0"
          geometry={nodes.inmx7m60i_body2001_bmwx72_0.geometry}
          material={materials.PaletteMaterial001}
          rotation={[-Math.PI / 2, 0, 0]}
          ref={body2001Ref}
        />
        <mesh
          name="inmx7m60i_bodyshell_bodyshell6_0"
          geometry={nodes.inmx7m60i_bodyshell_bodyshell6_0.geometry}
          material={materials.PaletteMaterial001}
          rotation={[-Math.PI / 2, 0, 0]}
          ref={bodyshellRef}
        />
        <mesh
          name="inmx7m60i_bodyshell_inmx7m60i_logo_0"
          geometry={nodes.inmx7m60i_bodyshell_inmx7m60i_logo_0.geometry}
          material={materials.inmx7m60i_logo}
          rotation={[-Math.PI / 2, 0, 0]}
          ref={bodyshellLogoRef}
        />
        <mesh
          name="inmx7m60i_gateglass_inmx7m60i_glass_0"
          geometry={nodes.inmx7m60i_gateglass_inmx7m60i_glass_0.geometry}
          material={materials.PaletteMaterial002}
          rotation={[-Math.PI / 2, 0, 0]}
          ref={tailgateGlassRef}
        />
        <mesh
          name="inmx7m60i_headlights1_inmx7m60i_running_r_0"
          geometry={nodes.inmx7m60i_headlights1_inmx7m60i_running_r_0.geometry}
          material={materials.PaletteMaterial004}
          rotation={[-Math.PI / 2, 0, 0]}
          ref={headlightsRef}
        />
        <mesh
          name="inmx7m60i_ltaillight_inmx7m60i_signalL_0"
          geometry={nodes.inmx7m60i_ltaillight_inmx7m60i_signalL_0.geometry}
          material={materials.PaletteMaterial003}
          rotation={[-Math.PI / 2, 0, 0]}
          ref={tailLightsRef}
        />
        <group name="inmx7m60i_dash" rotation={[-Math.PI / 2, 0, 0]} >
          <mesh
            name="inmx7m60i_dash_inmx7m60i_carbon_interior_0"
            geometry={nodes.inmx7m60i_dash_inmx7m60i_carbon_interior_0.geometry}
            material={materials.inmx7m60i_carbon_interior}
            ref={dashCarbonInteriorRef}
          />
          <mesh
            name="inmx7m60i_dash_inmx7m60i_dashscreen_0"
            geometry={nodes.inmx7m60i_dash_inmx7m60i_dashscreen_0.geometry}
            material={materials.inmx7m60i_dashscreen}
            ref={dashScreenRef}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload(glb);