/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 C:\Users\MADIHA\Desktop\Blenspark-revamp\src\Components\3DConfigurator\bmw_x7_m60i.glb --transform 
Files: C:\Users\MADIHA\Desktop\Blenspark-revamp\src\Components\3DConfigurator\bmw_x7_m60i.glb [19.43MB] > C:\Users\MADIHA\Desktop\Blenspark-revamp\src\Components\3DConfigurator\bmw_x7_m60i-transformed.glb [1.54MB] (92%)
Author: KOElkast1007 (https://sketchfab.com/koelkastasbers)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/bmw-x7-m60i-5664218111d345c6b79c64ae48c6dd8b
Title: BMW X7 M60i
*/

import React from 'react'
import { useState } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import model from "./bmw_x7_m60i-transformed.glb"
export function Car(props) {
  const group = React.useRef()
  const { nodes, materials, animations } = useGLTF(model)
  const { actions } = useAnimations(animations, group)
  React.useEffect(() => {
    if (actions) {
      console.log("Available animation names:", Object.keys(actions));
    }
  }, [actions]);
  const [isPlaying, setIsPlaying] = useState(false);

  const handleClick = () => {
    const action = actions["Doors opened"];
    if (!action) return;

    if (isPlaying) {
      action.paused = true;
    } else {
      action.reset().play();
      action.paused = false;
    }

    setIsPlaying(!isPlaying);
  };
  return (
    <group ref={group} {...props} dispose={null} onClick={handleClick}>
      <group name="Sketchfab_Scene">
        <group name="inmx7m60i_chassis" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="inmx7m60i_doorfl" position={[0.796, -0.811, -0.352]}>
            <mesh name="inmx7m60i_doorfl_inmx7m60i_wheel_03a_0" geometry={nodes.inmx7m60i_doorfl_inmx7m60i_wheel_03a_0.geometry} material={materials.PaletteMaterial001} />
            <mesh name="inmx7m60i_doorfl_inmx7m60i_glass_0" geometry={nodes.inmx7m60i_doorfl_inmx7m60i_glass_0.geometry} material={materials.PaletteMaterial002} />
            <mesh name="inmx7m60i_doorfl_inmx7m60i_signalL_0" geometry={nodes.inmx7m60i_doorfl_inmx7m60i_signalL_0.geometry} material={materials.PaletteMaterial004} />
            <mesh name="inmx7m60i_doorfl_inmx7m60i_leather1_0" geometry={nodes.inmx7m60i_doorfl_inmx7m60i_leather1_0.geometry} material={materials.inmx7m60i_leather1} />
          </group>
          <group name="inmx7m60i_doorrl" position={[0.804, 0.176, 0.677]}>
            <mesh name="inmx7m60i_doorrl_inmx7m60i_wheel_03a_0" geometry={nodes.inmx7m60i_doorrl_inmx7m60i_wheel_03a_0.geometry} material={materials.PaletteMaterial001} />
            <mesh name="inmx7m60i_doorrl_inmx7m60i_glass_0" geometry={nodes.inmx7m60i_doorrl_inmx7m60i_glass_0.geometry} material={materials.PaletteMaterial002} />
            <mesh name="inmx7m60i_doorrl_inmx7m60i_leather1_0" geometry={nodes.inmx7m60i_doorrl_inmx7m60i_leather1_0.geometry} material={materials.inmx7m60i_leather1} />
          </group>
          <group name="inmx7m60i_doorfr" position={[-0.807, -0.818, 0.651]}>
            <mesh name="inmx7m60i_doorfr_inmx7m60i_wheel_03a_0" geometry={nodes.inmx7m60i_doorfr_inmx7m60i_wheel_03a_0.geometry} material={materials.PaletteMaterial001} />
            <mesh name="inmx7m60i_doorfr_inmx7m60i_glass_0" geometry={nodes.inmx7m60i_doorfr_inmx7m60i_glass_0.geometry} material={materials.PaletteMaterial002} />
            <mesh name="inmx7m60i_doorfr_inmx7m60i_signalL_0" geometry={nodes.inmx7m60i_doorfr_inmx7m60i_signalL_0.geometry} material={materials.PaletteMaterial004} />
            <mesh name="inmx7m60i_doorfr_inmx7m60i_leather1_0" geometry={nodes.inmx7m60i_doorfr_inmx7m60i_leather1_0.geometry} material={materials.inmx7m60i_leather1} />
          </group>
          <group name="inmx7m60i_doorrr" position={[-0.804, 0.165, 0.69]}>
            <mesh name="inmx7m60i_doorrr_inmx7m60i_wheel_03a_0" geometry={nodes.inmx7m60i_doorrr_inmx7m60i_wheel_03a_0.geometry} material={materials.PaletteMaterial001} />
            <mesh name="inmx7m60i_doorrr_inmx7m60i_glass_0" geometry={nodes.inmx7m60i_doorrr_inmx7m60i_glass_0.geometry} material={materials.PaletteMaterial002} />
            <mesh name="inmx7m60i_doorrr_inmx7m60i_leather1_0" geometry={nodes.inmx7m60i_doorrr_inmx7m60i_leather1_0.geometry} material={materials.inmx7m60i_leather1} />
          </group>
        </group>
        <mesh name="m_m_tire_f_mm_tire_protector_F_0" geometry={nodes.m_m_tire_f_mm_tire_protector_F_0.geometry} material={materials.PaletteMaterial001} position={[0.72, 0.353, 1.376]} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh name="inmx7m60i_dash_inmx7m60i_wheel_03a_0" geometry={nodes.inmx7m60i_dash_inmx7m60i_wheel_03a_0.geometry} material={materials.PaletteMaterial001} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh name="inmx7m60i_dash_inmx7m60i_leather1_0" geometry={nodes.inmx7m60i_dash_inmx7m60i_leather1_0.geometry} material={materials.inmx7m60i_leather1} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh name="inmx7m60i_dash_inmx7m60i_carbon_interior_0" geometry={nodes.inmx7m60i_dash_inmx7m60i_carbon_interior_0.geometry} material={materials.inmx7m60i_carbon_interior} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh name="inmx7m60i_dash_inmx7m60i_dashscreen_0" geometry={nodes.inmx7m60i_dash_inmx7m60i_dashscreen_0.geometry} material={materials.inmx7m60i_dashscreen} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh name="inmx7m60i_chassis_inmx7m60i_carpet_0" geometry={nodes.inmx7m60i_chassis_inmx7m60i_carpet_0.geometry} material={materials.inmx7m60i_carpet} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh name="inmx7m60i_tailgate_inmx7m60i_glass_0" geometry={nodes.inmx7m60i_tailgate_inmx7m60i_glass_0.geometry} material={materials.PaletteMaterial002} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh name="inmx7m60i_tailgate_inmx7m60i_logo_0" geometry={nodes.inmx7m60i_tailgate_inmx7m60i_logo_0.geometry} material={materials.inmx7m60i_logo} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh name="inmx7m60i_headlights1_inmx7m60i_running_r_0" geometry={nodes.inmx7m60i_headlights1_inmx7m60i_running_r_0.geometry} material={materials.PaletteMaterial003} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh name="inmx7m60i_tailgatelights_inmx7m60i_signalL_0" geometry={nodes.inmx7m60i_tailgatelights_inmx7m60i_signalL_0.geometry} material={materials.PaletteMaterial004} rotation={[-Math.PI / 2, 0, 0]} />
      </group>
    </group>
  )
}

useGLTF.preload('/bmw_x7_m60i-transformed.glb')
