/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 C:\Users\MADIHA\Desktop\BlenSpark\Blenspark-revamp\public\Sofa1.glb --transform 
Files: C:\Users\MADIHA\Desktop\BlenSpark\Blenspark-revamp\public\Sofa1.glb [31.39MB] > C:\Users\MADIHA\Desktop\BlenSpark\Blenspark-revamp\Sofa1-transformed.glb [2.24MB] (93%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'
import glb from "./Sofa12-transformed.glb"
import { useEffect,useRef } from 'react'
export function Sofa(props) {
  const { nodes, materials } = useGLTF(glb)
    const Stands = useRef(null);
    const Cussion002 = useRef(null);
    const Taylor_Sofa001 = useRef(null);
    useEffect(() => {
      const ref = {
        Stands: Stands,
        Cussion002: Cussion002,
        Taylor_Sofa001: Taylor_Sofa001,
      }
      props.onRefsReady(ref, "sofa");
    }, [])
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Geometry.geometry} material={materials.Sofa} position={[0, 0.032, 0]} rotation={[Math.PI / 2, 0, 0]} ref={Taylor_Sofa001} />
      <mesh geometry={nodes.Geometry003.geometry} material={materials.Sofa} position={[0, 0.032, 0]} rotation={[Math.PI / 2, 0, 0]} />
      {props.woodStand&& <mesh geometry={nodes.Geometry004.geometry} material={materials.Wood} position={[0, 0.001, 0]} rotation={[Math.PI / 2, 0, 0]} />}
      {props.metalStand && <mesh geometry={nodes.Geometry005.geometry} material={materials['Steel stand']} position={[0, 0.001, 0]} rotation={[Math.PI / 2, 0, 0]} />}
      {props.sliverStand &&<mesh geometry={nodes.Geometry006.geometry} material={materials['Gold stand']} position={[0, 0.001, 0]} rotation={[Math.PI / 2, 0, 0]} />}
    </group>
  )
}

useGLTF.preload('/Sofa1-transformed.glb')
