/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 C:\Users\MADIHA\Desktop\BlenSpark\Blenspark-revamp\public\Sofa.glb --transform 
Files: C:\Users\MADIHA\Desktop\BlenSpark\Blenspark-revamp\public\Sofa.glb [31.33MB] > C:\Users\MADIHA\Desktop\BlenSpark\Blenspark-revamp\Sofa-transformed.glb [2.23MB] (93%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'
import { useRef, useEffect } from 'react'
import glb from "./Sofa-transformed.glb"
export function Sofa(props) {
  const { nodes, materials } = useGLTF(glb)
  const Stands = useRef(null);
  const Plane = useRef(null);
  const Cussion002 = useRef(null);
  const Cussion001 = useRef(null);
  const Back_seat_R = useRef(null);
  const Taylor_Sofa001 = useRef(null);
  useEffect(() => {
    const ref = {
      Stands: Stands,
      Plane: Plane,
      Cussion002: Cussion002,
      Cussion001: Cussion001,
      Back_seat_R: Back_seat_R,
      Taylor_Sofa001: Taylor_Sofa001,
    }
    props.onRefsReady(ref, "sofa");
  }, [])
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Geometry.geometry} material={materials.Sofa} position={[0, 0.032, 0]} rotation={[Math.PI / 2, 0, 0]} ref={Taylor_Sofa001} />
      <mesh geometry={nodes.Geometry003.geometry} material={materials.Sofa} position={[0, 0.032, 0]} rotation={[Math.PI / 2, 0, 0]} ref={Cussion002} />
      {props.Stand ?
        <mesh geometry={nodes.Geometry004.geometry} material={materials.Wood} position={[0, 0.001, 0]} rotation={[Math.PI / 2, 0, 0]} /> :
        <mesh geometry={nodes.Geometry005.geometry} material={materials['Steel stand']} position={[0, 0.001, 0]} rotation={[Math.PI / 2, 0, 0]} />}
    </group>
  )
}

useGLTF.preload('/Sofa-transformed.glb')
