/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 C:/Users/Hamza-Asif/OneDrive/Desktop/BlenSpark Re/Blenspark-revamp/src/assets/GLBs/New folder/GLB Black V/Untitled.glb --transform 
Files: C:/Users/Hamza-Asif/OneDrive/Desktop/BlenSpark Re/Blenspark-revamp/src/assets/GLBs/New folder/GLB Black V/Untitled.glb [16.15MB] > C:\Users\Hamza-Asif\OneDrive\Desktop\BlenSpark Re\Blenspark-revamp\src\Components\3DConfigurator\Untitled-transformed.glb [821.87KB] (95%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'
import model from './Untitled-transformed.glb'
export function Model(props) {
  const { nodes, materials } = useGLTF(model)
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Main.geometry} material={materials.Main} position={[1.47, 0.091, 2.088]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={[-0.012, 0.012, 0.012]} />
      <mesh geometry={nodes.Stitches.geometry} material={materials.Stitches} position={[1.47, 0.091, 2.088]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={[-0.012, 0.012, 0.012]} />
    </group>
  )
}

useGLTF.preload('/Untitled-transformed.glb')
